---
- name: Disable remote root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no"
  notify: restart sshd

- name: Enable deb-src list
  lineinfile: dest=/etc/apt/sources.list
              regexp='^deb-src'
              line='deb-src http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi'
              state=present
  sudo: True

- name: Upgrade APT
  apt: upgrade=dist
  notify: reboot

- name: Add Common Packages
  apt: pkg={{item}} state=installed
  with_items:
       - screen
       - vim
       - git
       - npm
